# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Onnen Build crkbd'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main-pi.yml
    with:
      keyboard: '["crkbd"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      rules: '[OLED_ENABLE = yes\nOLED_DRIVER = SSD1306\n"]'
